# -*- mode: python -*-

Import("env")

env.Library(
    target='net',
    source=[
        'http_controller.cc',
        'hatch_response.cc',
        'replication_server.cc',
        'replication_outbound.cc',
        'partition_server.cc',
        'partition_outbound.cc',
        '#/gen-cpp/Replication.cpp',
        '#/gen-cpp/Partition.cpp'
    ])
