# -*- mode: python -*-

Import('env')

env.Library(
    target='db',
    source=[
        'memory_store.cc',
        'types.cc',
    ]
)

env.Program('memory_store_test',
    source=['memory_store_test.cc'],
    LIBS=['db'],
    LIBPATH=['.'])
