#!/bin/bash

set -e

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd`
popd > /dev/null

set -ev

rm -rf $SCRIPTPATH/../lib/mongoose
git clone git@github.com:Gregwar/mongoose-cpp.git $SCRIPTPATH/../lib/mongoose
cd $SCRIPTPATH/../lib/mongoose
git reset --hard e7c87d3b9c79cffce41752583544586ec6ad365b

rm -rf $SCRIPTPATH/../lib/jsoncpp
git clone --depth=1 --branch=1.7.5 git@github.com:open-source-parsers/jsoncpp.git $SCRIPTPATH/../lib/jsoncpp
cd $SCRIPTPATH/../lib/jsoncpp


rm -rf .git
