# -*- mode: python -*-

Import('env')

env.Library(
    target='io',
    source=[
        'buffer_manager.cc',
        'buffer.cc'
    ]
)

env.Program(
    target='buffer_manager_test',
    source=[
        'buffer_manager_test.cc'
    ],
    LIBS=['io'],
    LIBPATH=['.'])
