# -*- mode: python -*-

Import('env')

env.SConscript(dirs=[
    'db',
    'net'
])

env.Program('server',
    source=['main.cc'],
    LIBS=['mongoose', 'jsoncpp', 'net'],
    LIBPATH=['#/lib/mongoose', '#/lib/jsoncpp/src/lib_json', 'net'])
