# -*- mode: python -*-

Import('env')

env.SConscript(dirs=[
    'db',
    'net'
])

env.Program('cs426_graph_server',
    source=['main.cc'],
    LIBS=['mongoose', 'jsoncpp', 'net', 'db'],
    LIBPATH=['#/lib/mongoose', '#/lib/jsoncpp/src/lib_json', 'net', 'db'])

env.Install('#', 'cs426_graph_server')
