# -*- mode: python -*-

Import('env')

env.SConscript(dirs=[
    'db',
    'net',
    'io'
])

env.Program('cs426_graph_server',
    source=['main.cc'],
    LIBS=['net', 'db', 'io', 'mongoose', 'jsoncpp', 'pthread'],
    LIBPATH=['#/lib/mongoose', '#/lib/jsoncpp/src/lib_json', 'net', 'db', 'io'])

env.Install('#', 'cs426_graph_server')
